env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  require: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
